### ISSUE TITLE
Jupyter Lab extensions fail to build

### ISSUE THREAD

**Issue by dr-kinder** [plotly/plotly.py#2223]
I am attempting to install Plotly extensions to the Jupyter Lab environment as described in the "JupyterLab Support (Python 3.5+)" instructions [here](https://plot.ly/python/getting-started/).

Whenever I attempt a build, or a `jupyterlab extension install ...` without the `--nobuild` option, installation fails.  The trouble comes from `npm`, but I cannot find any information about this error.

```
error Couldn't find any versions for "@types/d3" that matches "^[object Object]"
```

For more information on the problem, this is the result of an attempted build:
```
$ jupyter lab build
[LabBuildApp] JupyterLab 1.2.6
[LabBuildApp] Building in /usr/local/share/jupyter/lab
[LabBuildApp] Building jupyterlab assets (build:prod:minimize)
An error occured.
RuntimeError: npm dependencies failed to install
See the log file for details:  ...
```

These are the contents of the log file:

```
[LabBuildApp] Building in /usr/local/share/jupyter/lab
[LabBuildApp] Yarn configuration loaded.
[LabBuildApp] Node v13.8.0

[LabBuildApp] Building jupyterlab assets (build:prod:minimize)
[LabBuildApp] > node /usr/local/lib/python3.7/site-packages/jupyterlab/staging/yarn.js install --non-interactive
[LabBuildApp] yarn install v1.15.2
[1/5] Validating package.json...
[2/5] Resolving packages...
warning jupyterlab-plotly > plotly.js > regl-splom > left-pad@1.3.0: use String.prototype.padStart()
warning jupyterlab-plotly > plotly.js > regl-error2d > bubleify > buble > os-homedir@2.0.0: This is not needed anymore. Use `require('os').homedir()` instead.
error Couldn't find any versions for "@types/d3" that matches "^[object Object]"
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

[LabBuildApp] npm dependencies failed to install
...
```

I successfully installed plotly and d3 with `npm`.
I am running Python 3.7.6, Jupyter Lab 1.2.6, IPyWidgets 7.5.1, Yarn 1.22.0, and Node 13.8.0.
All Python packages were installed using `pip`.

**Comment by nicolaskruchten** [comment]
Hmm I think I might have an idea... can you please share the output of `jupyter labextension list`?

Also, please note that you don’t need to use NPM yourself directly to install anything: Jupyter Lab uses NPM under the hood so that’s why the error comes from there but there’s nothing you should need to do yourself with with :)

**Comment by flrs-edf** [comment]
I have the same issue. Here is the output of `jupyter labextension list` (redacted: `***`):

```
(***) C:\Users\***>jupyter labextension list
JupyterLab v1.2.6
Known labextensions:
   app dir: C:\Users\***\AppData\Local\Continuum\anaconda3\envs\***\share\jupyter\lab
        @jupyter-widgets/jupyterlab-manager v1.1.0 enabled  ok
        @jupyterlab/toc v2.0.0-rc.0 enabled  ok
        arcgis-map-ipywidget v1.6.2-post1 enabled  ok
        jupyterlab-plotly v1.5.1 enabled  ok
        plotlywidget v1.5.1 enabled  ok

Build recommended, please run `jupyter lab build`:
    arcgis-map-ipywidget needs to be included in build
    @jupyter-widgets/jupyterlab-manager needs to be included in build
    @jupyterlab/toc needs to be included in build
    plotlywidget needs to be included in build
    jupyterlab-plotly needs to be included in build
```

**Comment by nicolaskruchten** [comment]
Ok, and does the build succeed with versions 1.5.0 of the Plotly extensions?

**Comment by matdecac** [comment]
Hello, I am having the same error for a week. For now I am using orca to generate the graphs.

Same problem occurs with v1.5.0 of plotly extensions.

**Comment by mansenfranzen** [comment]
I'm having the exact same issue with a clean conda env and pip installs under Ubuntu 18.04LTS with python 3.6.7, jupyterlab 1.2.0, ipywidgets 7.5.1, plotly 4.5.1, plotly-express 0.4.1, nodejs 13.9.0.

**Comment by nicolaskruchten** [comment]
it would really help if everyone chiming in here could include the output of `jupyter labextension list` so we can triangulate where the conflict is coming from please :)

**Comment by matdecac** [comment]
Here is the Dockerfile I am using :
```
FROM ubuntu:rolling
RUN apt-get update && \ 
    apt-get upgrade -y && \
    apt-get install -y gcc python3 python-pip python3-venv npm && \
    rm -rf /var/lib/apt/lists/* && \
    rm /bin/sh && ln -s /bin/bash /bin/sh && \
    useradd user --home /home/user/ --create-home --shell /bin/bash
USER user
WORKDIR "/home/user/"
RUN mkdir -p venv && \
    python3 -m venv venv/ && \
    venv/bin/pip3 install --upgrade pip --no-cache-dir && \
    venv/bin/pip3 install --no-cache-dir \
        numpy \
        pandas \
        jupyterlab==1.2 \
        "ipywidgets==7.5" \
        plotly==4.5.1
#RUN export NODE_OPTIONS=--max-old-space-size=4096 && \
#    venv/bin/jupyter labextension install @jupyter-widgets/jupyterlab-manager@1.1 --no-build && \
#    venv/bin/jupyter labextension install plotlywidget@1.5.1 --no-build && \
#    venv/bin/jupyter labextension install jupyterlab-plotly@1.5.1 --no-build && \
#    venv/bin/jupyter lab build && \
#    unset NODE_OPTIONS
```


Those are warnings and error that happens during build
```
warning plotlywidget > plotly.js > regl-splom > left-pad@1.3.0: use String.prototype.padStart()
warning plotlywidget > plotly.js > regl-error2d > bubleify > buble > os-homedir@2.0.0: This is not needed anymore. Use `require('os').homedir()` instead.
error Couldn't find any versions for "@types/d3" that matches "^[object Object]"
```

Here is the output of `jupyter labextension list`: 
```
JupyterLab v1.2.0
Known labextensions:
   app dir: /home/user/venv/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v1.1.0  enabled  OK
        jupyterlab-plotly v1.5.1  enabled  OK
        plotlywidget v1.5.1  enabled  OK

Build recommended, please run `jupyter lab build`:
    @jupyter-widgets/jupyterlab-manager needs to be included in build
    plotlywidget needs to be included in build
    jupyterlab-plotly needs to be included in build
```

Here is the output from my last working setup of `jupyter labextension list`:
```
JupyterLab v1.2.3
Known labextensions:
   app dir: /media/CR750/home/comptadecac/venv/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v1.1.0  enabled  OK
        jupyterlab-plotly v1.3.0  enabled  OK
        plotlywidget v1.3.0  enabled  OK
```

I modified my docker to use v1.3 of plotly extensions, but it throws the same error, and same result for `jupyter labextension list`.

Hopes it help

**Comment by nicolaskruchten** [comment]
Extremely helpful, thank you @matdecac ! This error doesn’t have the same cause as the one I have previously encountered, so I will have to investigate more fully next week.

If anyone else encounters an installation problem, please continue to provide similar details so I can determine if we have one or many issues to tackle :)

**Comment by mansenfranzen** [comment]
@nicolaskruchten here comes the `jupyter labextension list`:

```
JupyterLab v1.2.0
Known labextensions:
   app dir: /***/envs/env_dist_dev/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v1.1.0  enabled  OK
        jupyterlab-plotly v1.5.1  enabled  OK
        plotlywidget v1.5.1  enabled  OK

Build recommended, please run `jupyter lab build`:
    @jupyter-widgets/jupyterlab-manager needs to be included in build
    plotlywidget needs to be included in build
    jupyterlab-plotly needs to be included in build
```

**Comment by dr-kinder** [comment]
Here is the output of `jupyter labextension list` on my system:

```
$ jupyter labextension list
JupyterLab v1.2.6
Known labextensions:
   app dir: /usr/local/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v1.1.0  enabled  OK
        @pyviz/jupyterlab_pyviz v0.8.0  enabled  OK
        jupyter-matplotlib v0.3.0  enabled  OK
        jupyterlab-plotly v1.5.1  enabled  OK
        jupyterlab_bokeh v1.0.0  enabled  OK
        plotlywidget v1.5.1  enabled  OK

Build recommended, please run `jupyter lab build`:
    plotlywidget needs to be included in build
    @pyviz/jupyterlab_pyviz needs to be included in build
    jupyter-matplotlib needs to be included in build
    jupyterlab_bokeh needs to be included in build
    @jupyter-widgets/jupyterlab-manager needs to be included in build
    jupyterlab-plotly needs to be included in build
```

**Comment by zezuladp** [comment]
Same issue here.
```
root@39d6358ab159:/# jupyter labextension install --no-build jupyterlab-plotly@1.5.1
root@39d6358ab159:/# jupyter lab build
[LabBuildApp] JupyterLab 1.2.5
[LabBuildApp] Building in /usr/local/share/jupyter/lab
[LabBuildApp] Building jupyterlab assets (build:prod:minimize)
An error occured.
RuntimeError: npm dependencies failed to install
See the log file for details:  /tmp/jupyterlab-debug-ot4fa8pa.log
root@39d6358ab159:/# jupyter labextension list
JupyterLab v1.2.5
Known labextensions:
   app dir: /usr/local/share/jupyter/lab
        jupyter-threejs v2.1.1  enabled  OK
        jupyterlab-datawidgets v6.2.0  enabled  OK
        jupyterlab-plotly v1.5.1  enabled  OK

Build recommended, please run `jupyter lab build`:
    jupyter-threejs needs to be included in build
    jupyterlab-datawidgets needs to be included in build
    jupyterlab-plotly needs to be included in build
```

where my logfile says:
```
[LabBuildApp] Building in /usr/local/share/jupyter/lab
[LabBuildApp] Yarn configuration loaded.
[LabBuildApp] Node v12.16.1

[LabBuildApp] Building jupyterlab assets (build:prod:minimize)
[LabBuildApp] > node /usr/local/lib/python3.6/dist-packages/jupyterlab/staging/yarn.js install --non-interactive
[LabBuildApp] yarn install v1.15.2
[1/5] Validating package.json...
[2/5] Resolving packages...
warning jupyterlab-plotly > plotly.js > regl-splom > left-pad@1.3.0: use String.prototype.padStart()
warning jupyterlab-plotly > plotly.js > point-cluster > bubleify > buble > os-homedir@2.0.0: This is not needed anymore. Use `require('os').homedir()` instead.
error Couldn't find any versions for "@types/d3" that matches "^[object Object]"
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

[LabBuildApp] npm dependencies failed to install
[LabBuildApp] Traceback (most recent call last):

[LabBuildApp]   File "/usr/local/lib/python3.6/dist-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

[LabBuildApp]   File "/usr/local/lib/python3.6/dist-packages/jupyterlab/labapp.py", line 98, in start
    command=command, app_options=app_options)

[LabBuildApp]   File "/usr/local/lib/python3.6/dist-packages/jupyterlab/commands.py", line 459, in build
    command=command, clean_staging=clean_staging)

[LabBuildApp]   File "/usr/local/lib/python3.6/dist-packages/jupyterlab/commands.py", line 660, in build
    raise RuntimeError(msg)

[LabBuildApp] RuntimeError: npm dependencies failed to install

[LabBuildApp] Exiting application: JupyterLab
```

**Comment by spalvadeau** [comment]
Hi, I have the same issue. It appeared suddenly. Two days ago, build was successful. Today, I created a new conda env (copy from a environment.yml with the exact same packages) and it fails.
Here is the output of `jupyter labextension list`

```
JupyterLab v1.2.6
Known labextensions:
   app dir: C:\Users\Samuel.PALVADEAU\projects\OpenClassRooms\DataAnalyst\P6\conda-env\share\jupyter\lab
        @jupyter-widgets/jupyterlab-manager v1.1.0 enabled  ok
        @jupyterlab/toc v1.0.1 enabled  ok
        jupyterlab-plotly v1.5.1 enabled  ok
        plotlywidget v1.5.1 enabled  ok

Build recommended, please run `jupyter lab build`:
    @jupyter-widgets/jupyterlab-manager needs to be included in build
    plotlywidget needs to be included in build
    jupyterlab-plotly needs to be included in build
```
and the log file
```
[LabBuildApp] Building in C:\Users\Samuel.PALVADEAU\projects\OpenClassRooms\DataAnalyst\P6\conda-env\share\jupyter\lab
[LabBuildApp] Yarn configuration loaded.
[LabBuildApp] Node v13.9.0

[LabBuildApp] Building jupyterlab assets (build:prod:minimize)
[LabBuildApp] > node C:\Users\Samuel.PALVADEAU\projects\OpenClassRooms\DataAnalyst\P6\conda-env\lib\site-packages\jupyterlab\staging\yarn.js install --non-interactive
[LabBuildApp] yarn install v1.15.2
[1/5] Validating package.json...
[2/5] Resolving packages...
warning jupyterlab-plotly > plotly.js > regl-splom > left-pad@1.3.0: use String.prototype.padStart()
warning jupyterlab-plotly > plotly.js > point-cluster > bubleify > buble > os-homedir@2.0.0: This is not needed anymore. Use `require('os').homedir()` instead.
error Couldn't find any versions for "@types/d3" that matches "^[object Object]"
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

[LabBuildApp] npm dependencies failed to install
[LabBuildApp] Traceback (most recent call last):

[LabBuildApp]   File "C:\Users\Samuel.PALVADEAU\projects\OpenClassRooms\DataAnalyst\P6\conda-env\lib\site-packages\jupyterlab\debuglog.py", line 47, in debug_logging
    yield

[LabBuildApp]   File "C:\Users\Samuel.PALVADEAU\projects\OpenClassRooms\DataAnalyst\P6\conda-env\lib\site-packages\jupyterlab\labapp.py", line 97, in start
    build(name=self.name, version=self.version,

[LabBuildApp]   File "C:\Users\Samuel.PALVADEAU\projects\OpenClassRooms\DataAnalyst\P6\conda-env\lib\site-packages\jupyterlab\commands.py", line 458, in build
    return handler.build(name=name, version=version, static_url=static_url,

[LabBuildApp]   File "C:\Users\Samuel.PALVADEAU\projects\OpenClassRooms\DataAnalyst\P6\conda-env\lib\site-packages\jupyterlab\commands.py", line 660, in build
    raise RuntimeError(msg)

[LabBuildApp] RuntimeError: npm dependencies failed to install

[LabBuildApp] Exiting application: JupyterLab
```

**Comment by nicolaskruchten** [comment]
Ok so we released versions 1.5.1 of the extensions this past Wednesday... maybe something in there causes this but some people are reporting the same issue with the weeks-old 1.5.0 versions of the extensions. If anyone has a chance to try with a clean environment and the 1.5.0 extensions I’d love to know if this still happens. I’ve not been able to reproduce this issue myself yet.

**Comment by mansenfranzen** [comment]
Tested extensions with explicit 1.5.0 version under fresh win10 env but got same error :-(.

**jupyter labextension list**:

```
JupyterLab v1.2.0
Known labextensions:
   app dir: c:\***\miniconda3\envs\test_juplab\share\jupyter\lab
        @jupyter-widgets/jupyterlab-manager v1.1.0 enabled  ok
        jupyterlab-plotly v1.5.0 enabled  ok
        plotlywidget v1.5.0 enabled  ok

Build recommended, please run `jupyter lab build`:
    @jupyter-widgets/jupyterlab-manager needs to be included in build
    plotlywidget needs to be included in build
    jupyterlab-plotly needs to be included in build
```

**Error log**:

```
jupyter lab build
[LabBuildApp] JupyterLab 1.2.0
[LabBuildApp] Building in c:\***\miniconda3\envs\test_juplab\share\jupyter\lab
[LabBuildApp] Building jupyterlab assets (build:prod:minimize)
An error occured.
RuntimeError: npm dependencies failed to install
```

```
[LabBuildApp] Building in c:\***\miniconda3\envs\test_juplab\share\jupyter\lab
[LabBuildApp] Yarn configuration loaded.
[LabBuildApp] Node v10.13.0

[LabBuildApp] Building jupyterlab assets (build:prod:minimize)
[LabBuildApp] > node c:\***\miniconda3\envs\test_juplab\lib\site-packages\jupyterlab\staging\yarn.js install --non-interactive
[LabBuildApp] yarn install v1.15.2
[1/5] Validating package.json...
[2/5] Resolving packages...
warning jupyterlab-plotly > plotly.js > regl-splom > left-pad@1.3.0: use String.prototype.padStart()
warning jupyterlab-plotly > plotly.js > point-cluster > bubleify > buble > os-homedir@2.0.0: This is not needed anymore. Use `require('os').homedir()` instead.
error Couldn't find any versions for "@types/d3" that matches "^[object Object]"
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

[LabBuildApp] npm dependencies failed to install
[LabBuildApp] Traceback (most recent call last):

[LabBuildApp]   File "c:\***\miniconda3\envs\test_juplab\lib\site-packages\jupyterlab\debuglog.py", line 47, in debug_logging
    yield

[LabBuildApp]   File "c:\***\miniconda3\envs\test_juplab\lib\site-packages\jupyterlab\labapp.py", line 98, in start
    command=command, app_options=app_options)

[LabBuildApp]   File "c:\***\miniconda3\envs\test_juplab\lib\site-packages\jupyterlab\commands.py", line 459, in build
    command=command, clean_staging=clean_staging)

[LabBuildApp]   File "c:\***\miniconda3\envs\test_juplab\lib\site-packages\jupyterlab\commands.py", line 660, in build
    raise RuntimeError(msg)

[LabBuildApp] RuntimeError: npm dependencies failed to install

[LabBuildApp] Exiting application: JupyterLab
```

**Comment by peterblazejewicz** [comment]
> yet to find a workaround though

folks, you could change reference in the CI build (or whenever you're specifying NPM related content) to reference `@types/plotly.js@1.44.24` - this just installs type definitions and probably have not diret impact on the Python related stuff I guess.
There is invalid entry in the NPM package registration, as described here:
microsoft/types-publisher#746
Thanks!

**Comment by sutiv** [comment]
is there any workaround?

**Comment by txu0393** [comment]
I'm also running into the same issue.
Funnily enough, the plotly lab extension was able to install early last week.
I'm trying to install a new lab extension (dask-labextension@v1.1.0), which is causing all the plotly extensions to rebuild and now I'm running into the same error as everyone else.

Output:
```
# jupyter labextension list
JupyterLab v1.1.4
Known labextensions:
   app dir: /opt/anaconda3/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v1.0.3  enabled  OK
        jupyterlab-plotly v1.2.0  enabled  OK
        plotlywidget v1.2.0  enabled  OK

# jupyter labextension install --no-build dask-labextension@v1.1.0 \
#      && jupyter lab build --debug \
#      && jupyter lab clean --debug
[LabBuildApp] Searching ['/root', '/root/.jupyter', '/opt/anaconda3/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[LabBuildApp] Looking for jupyter_config in /etc/jupyter
[LabBuildApp] Looking for jupyter_config in /usr/local/etc/jupyter
[LabBuildApp] Looking for jupyter_config in /opt/anaconda3/etc/jupyter
[LabBuildApp] Looking for jupyter_config in /root/.jupyter
[LabBuildApp] Looking for jupyter_config in /root
[LabBuildApp] Looking for JupyterLab_config in /etc/jupyter
[LabBuildApp] Looking for JupyterLab_config in /usr/local/etc/jupyter
[LabBuildApp] Looking for JupyterLab_config in /opt/anaconda3/etc/jupyter
[LabBuildApp] Looking for JupyterLab_config in /root/.jupyter
[LabBuildApp] Looking for JupyterLab_config in /root
[LabBuildApp] JupyterLab 1.1.4
[LabBuildApp] Building in /opt/anaconda3/share/jupyter/lab
[LabBuildApp] Node v10.13.0

[LabBuildApp] Building jupyterlab assets (build:prod:minimize)
[LabBuildApp] > node /opt/anaconda3/lib/python3.7/site-packages/jupyterlab/staging/yarn.js install --non-interactive
/[LabBuildApp] yarn install v1.15.2
[1/5] Validating package.json...
[2/5] Resolving packages...
warning jupyterlab-plotly > plotly.js > regl-splom > left-pad@1.3.0: use String.prototype.padStart()
warning jupyterlab-plotly > plotly.js > ndarray-fill > cwise > static-module > through2 > xtend > object-keys@0.4.0: 
warning jupyterlab-plotly > plotly.js > regl-error2d > bubleify > buble > os-homedir@2.0.0: This is not needed anymore. Use `require('os').homedir()` instead.
error Couldn't find any versions for "@types/d3" that matches "^[object Object]"
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

[LabBuildApp] npm dependencies failed to install
[LabBuildApp] Traceback (most recent call last):

[LabBuildApp]   File "/opt/anaconda3/lib/python3.7/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

[LabBuildApp]   File "/opt/anaconda3/lib/python3.7/site-packages/jupyterlab/labapp.py", line 96, in start
    core_config=self.core_config)

[LabBuildApp]   File "/opt/anaconda3/lib/python3.7/site-packages/jupyterlab/commands.py", line 378, in build
    command=command, clean_staging=clean_staging)

[LabBuildApp]   File "/opt/anaconda3/lib/python3.7/site-packages/jupyterlab/commands.py", line 574, in build
    raise RuntimeError(msg)

[LabBuildApp] RuntimeError: npm dependencies failed to install

An error occured.
RuntimeError: npm dependencies failed to install
See the log file for details:  /tmp/jupyterlab-debug-aeoez37q.log
[LabBuildApp] Exiting application: JupyterLab

# jupyter labextension list
JupyterLab v1.1.4
Known labextensions:
   app dir: /opt/anaconda3/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v1.0.3  enabled  OK
        dask-labextension v1.1.0  enabled  OK
        jupyterlab-plotly v1.2.0  enabled  OK
        plotlywidget v1.2.0  enabled  OK

Build recommended, please run `jupyter lab build`:
    dask-labextension needs to be included in build
```

/tmp/jupyterlab-debug-aeoez37q.log:
`<Same contents of the output of the "jupyter labextension install" command>`

**Comment by abdalazizrashid** [comment]
Same problem with me!
```
 jupyter labextension list
JupyterLab v1.2.6
Known labextensions:
   app dir: /usr/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v1.1.0  enabled  OK
        jupyterlab-plotly v1.5.1  enabled  OK
        plotlywidget v1.5.1  enabled  OK

Build recommended, please run `jupyter lab build`:
    @jupyter-widgets/jupyterlab-manager needs to be included in build
    plotlywidget needs to be included in build
    jupyterlab-plotly needs to be included in build
```

**Comment by nicolaskruchten** [comment]
OK I think I have enough info to fix this, I should have a fix in a day or two, thanks for the information everyone!

**Comment by nicolaskruchten** [comment]
The root cause of this problem appears to be a bad version of https://www.npmjs.com/package/@types/plotly.js which is something we depend on but do not maintain. 

In principle I could just pin the version to a known-working one here: https://github.com/plotly/plotly.py/blob/master/packages/javascript/jupyterlab-plotly/package.json#L35 and release versions 1.5.2 of our extensions. I will try to do this tonight (Pacific Time).

**Comment by peterblazejewicz** [comment]
@nicolaskruchten 
Yup, it would work, some detials here:
https://github.com/microsoft/types-publisher/issues/746#issuecomment-590216750

**Comment by nicolaskruchten** [comment]
@peterblazejewicz yes, thanks, your comment above pointed the way. I rather wish that the `types` project did a bit more QA on stuff like this ;)

**Comment by nicolaskruchten** [comment]
OK I've pushed up versions 1.5.2 of the extensions, so that should resolve the current issue!

**Comment by dr-kinder** [comment]
Thanks for your quick work on this.  I followed the instructions [here](https://plot.ly/python/getting-started/) again, changing all `@1.5.1` references to `@1.5.2` and the installation and build worked perfectly.

**Comment by enahwe** [comment]
I had exactly the same issue since yesterday, I followed the same instructions as @dr-kinder said, and at last it works after more than twelve hours of investigation. Thanks guys

**Comment by andrei91ro** [comment]
Thank for your prompt intervention. However, now that the buld finishes cleanly, the extension is still not working. I am seeing only a blank container where the plot should be. If I use a widget, I only see a `loading widget ...` message that never changes.

I installed the exact versions (for python and JS versions of plotly) as stated in the update README.
The only difference is that I am using Jupyter lab 1.2.6 vs 1.2.0 from the Readme.

Can this be the cause of my problem?

The browser console contains the following output:
```
Could not instantiate widget manager-base.js:273:32
    _make_model manager-base.js:273
    l manager-base.js:44
    s manager-base.js:25
    s manager-base.js:17
Error: "Could not create a model."
    n utils.js:119
utils.js:119:20
    n utils.js:119
Exception opening new comm default.js:992:24
    _handleCommOpen default.js:992
Error: Module plotlywidget, semver range 1.5.2 is not registered as a widget module manager.js:305:18
Error: "Module plotlywidget, semver range 1.5.2 is not registered as a widget module"
    loadClass manager.js:305
    _make_model manager-base.js:263
    l manager-base.js:44
    s manager-base.js:25
    L manager-base.js:19
    L manager-base.js:15
    _make_model manager-base.js:257
    new_model manager-base.js:246
    l manager-base.js:44
    s manager-base.js:25
    L manager-base.js:19
    L manager-base.js:15
    new_model manager-base.js:232
    handle_comm_open manager-base.js:144
    _handleCommOpen manager.js:62
    _handleCommOpen default.js:990
default.js:111:74
    _msgChain default.js:111
Error: Module plotlywidget, semver range 1.5.2 is not registered as a widget module manager.js:305:18

​
```

**Comment by nicolaskruchten** [comment]
@andrei91ro that sounds like a different issue... could you please create a new one so that others can find it and contribute?

**Comment by GIShkl** [comment]
(base) C:\Users\10055>jupyter lab build
[LabBuildApp] JupyterLab 1.2.6
[LabBuildApp] Building in D:\Software\ANACONDA\share\jupyter\lab
[LabBuildApp] Building jupyterlab assets (build:prod:minimize)
An error occured.
RuntimeError: JupyterLab failed to build
See the log file for details:  C:\Users\10055\AppData\Local\Temp\jupyterlab-debug-kd3f83k8.log

(base) C:\Users\10055>jupyter labextension list
JupyterLab v1.2.6
Known labextensions:
   app dir: D:\Software\ANACONDA\share\jupyter\lab
        @jupyterlab/github v1.0.1 enabled  ok
        @jupyterlab/toc v2.0.0 enabled  ok
        @krassowski/jupyterlab-lsp v1.0.0 enabled  ok
        @krassowski/jupyterlab_go_to_definition v1.0.0 enabled  ok

Build recommended, please run `jupyter lab build`:
    @jupyterlab/github needs to be included in build
    @jupyterlab/toc needs to be included in build
    @krassowski/jupyterlab-lsp needs to be included in build
    @krassowski/jupyterlab_go_to_definition needs to be included in build

(base) C:\Users\10055>

**Comment by nicolaskruchten** [comment]
@GIShkl can you please open a new issue for this and include the contents of the log file?

**Comment by nicolaskruchten** [comment]
(in general, let's please not add on to old, closed issues like this and instead open up new ones :)
