### ISSUE TITLE
update_xaxes(categoryorder="total descending") does not work correctly on px.histogram

### ISSUE THREAD

**Issue by Kerybas** [plotly/plotly.py#2350]
Hello,
When using `update_xaxes(categoryorder="total descending")` on a histogram, I expect the bars to be reordered by size.
The following example, tested in a Notebook, will not work according to my expectation:
```python
import pandas as pd
import plotly.express as px

data =[['A','left'],['B','left'],['C','right'],['D','up'],['E','right'],['F','down'],
       ['A','right'],['B','righ'],['B','right'],['B','up'],['A','left'],['F','up'],
       ['B','left'],['F','left'],['B','right'],['A','up'],['A','right'],['F','down'],
      ]
df = pd.DataFrame(data, columns=['letter','direction'])
px.histogram(df, x='letter', color='direction').update_xaxes(categoryorder="total descending")
```
![image](https://user-images.githubusercontent.com/42703200/78333372-00592400-758a-11ea-97d2-0227ddd86bc3.png)

Note that the behavior is unclear to me. In certain condition, the order might be correct. For instance, if you change the last row to `['E','down']`, then the order of the plot is correct.

In any case, I would expect the same result than the following:
```python
import pandas as pd
import plotly.express as px

data =[['A','left'],['B','left'],['C','right'],['D','up'],['E','right'],['F','down'],
       ['A','right'],['B','righ'],['B','right'],['B','up'],['A','left'],['F','up'],
       ['B','left'],['F','left'],['B','right'],['A','up'],['A','right'],['E','down'],
      ]

df = pd.DataFrame(data, columns=['letter','direction'])
df['count'] = 1
df = df.groupby(['letter','direction'])['count'].sum().reset_index()
px.bar(df, x='letter', y='count', color='direction').update_xaxes(categoryorder="total descending")
```
![image](https://user-images.githubusercontent.com/42703200/78333685-92612c80-758a-11ea-8ac4-af5db5019851.png)

**Comment by nicolaskruchten** [comment]
Unfortunately I cannot reproduce this... your first example orders correctly for me:

![image](https://user-images.githubusercontent.com/203523/78360719-35af4300-7585-11ea-9793-df03237020b1.png)

And your second does also... Could you try upgrading to the latest version of `plotly` which is 4.6.0 to see if this is a bug we've already fixed?

**Comment by Kerybas** [comment]
So, I was indeed on 4.5.2 but I upgraded and still the same:
![image](https://user-images.githubusercontent.com/42703200/78379426-a16bcd00-75d2-11ea-8d90-d4439c7b0673.png)

Strange... What else could it be?
I'm on Win10 + Anaconda3.

**Comment by wcj365** [comment]
I have the same issue.
Plotly:  4.5.2
Pandas:  1.0.1

**Comment by audelorAd** [comment]
Hello,
I have the same issue too.
Sorting isn't working with histogram but with bar chart it's ok.
Tried with latest version **pandas : 1.1.2** & **plotly : 4.10.0**

![2020-09-23_10h03_53](https://user-images.githubusercontent.com/63049494/93984603-50b87e00-fd84-11ea-9dd1-2ded7fe64299.png)

**Comment by jframe-fid** [comment]
I see this same issue with histograms, and switches to bar fixes it. I would love for it to be fixed so I can move back to the simplicity of histograms.

plotly: 4.11.0
pandas: 1.0.5

**Comment by nicolaskruchten** [comment]
Are folks who are encountering this bug running JupyterLab? If so, please note that the version of the `jupyterlab-plotly` labextension must match the version of the `plotly` Python module to run correctly... See https://plotly.com/python/troubleshooting/#jupyterlab-problems for more details.

If this is happening in a "classic" Jupyter Notebook or is happening in JupyterLab with an up-to-date extension then there is definitely something to fix here.

Here is a Javascript-only version of the figure produced by this Python call: https://codepen.io/nicolaskruchten/pen/ExyWMZj ... if someone who is seeing this issue can please click on that link and tell me if things are rendering in or out of order (in the same browser/on the same machine as they're seeing the problem), that might help narrow down the possibilities!

**Comment by Kerybas** [comment]
Hello @nicolaskruchten, I just tested on:
- Win10 + Jupyter Notebook + Plotly 4.12 
- Manjaro + Jupyter Notebook + Plotly 4.11 

and the problem was there on both. However, your codepen looks fine.

**Comment by audelorAd** [comment]
@nicolaskruchten I'm testing in a Dash App and with Terminal with same result.

I'm working with data in this attach file ( [test_dataframe.txt](https://github.com/plotly/plotly.py/files/5444210/test_dataframe.txt) )  and running the following exmeple : 

```python
col = ['lib','type','year','sup']

# Get data with attach file
df = pd.DataFrame(data, columns=col)

fig1 = px.histogram(df, x='year', y='sup', color='type').update_xaxes(type="category", categoryorder="total descending")

fig1.show()

fig2 = px.histogram(df, x='lib', y='sup', color='type').update_xaxes(type="category", categoryorder="total descending")

fig2.show()
```

**fig1** is always displaying in the right order and **fig2** always displaying in the wrong order
![2020-10-27_10h21_16](https://user-images.githubusercontent.com/63049494/97281897-54856780-183e-11eb-851b-db154ecbaca5.png)

**Comment by Kerybas** [comment]
> ![2020-10-27_10h21_16](https://user-images.githubusercontent.com/63049494/97281897-54856780-183e-11eb-851b-db154ecbaca5.png)

I really can't guess a logic that would generate that order...!

**Comment by jframe-fid** [comment]
When I create a color by histogram, it never comes out correctly, and like @Kerybas I can't figure out how it's ordering things. Even if it acts up with more than one color bin, if I turn off all colors but one, it orders properly again. If I turn even one color back on though, it goes back to the really odd ordering.

**Comment by audelorAd** [comment]
> 
> I really can't guess a logic that would generate that order...!
> @audelorAd: you are studying Breton names, aren't you?!

Yes I am ;)

**Comment by jenna-jordan** [comment]
I am also having this issue, but with px.bar rather than px.histogram
Like @wcj365 said, the problem goes away if you don't pass a "color" argument. However, that kinda defeats the point of a stacked bar chart...
I am rendering this with streamlit, not in a jupyter notebook.
code:
```
df = df.sort_values(by=["company_count", "Category"])
    fig = px.bar(
        df,
        y="Keyword",
        x="company_count",
        color="Category",
        barmode="stack",
        template="plotly_white",
        orientation="h",
        hover_name="Keyword",
        text="company_count",
        color_discrete_sequence=px.colors.qualitative.Vivid,
    )
    fig.update_yaxes(
        type="category",
        categoryorder="total ascending")
```
Plot:
<img width="1007" alt="Screen Shot 2020-11-11 at 3 07 19 PM" src="https://user-images.githubusercontent.com/11811148/98859092-a2e65900-242f-11eb-8303-43901748ae71.png">

**Comment by nicolaskruchten** [comment]
OK, we've got a fix in the underlying JS engine, which will become available with version 4.13 of Plotly for Python. Hopefully that'll resolve all these issues!

**Comment by jframe-fid** [comment]
I've updated to plotly 4.13 today, and I'm still seeing the odd ordering behavior with px.histogram. Has anyone else seen this fixed updating to 4.13?

**Comment by nicolaskruchten** [comment]
Hmm ok, maybe there's more than one problem here :) @jframe-fid can you share some simple code that shows this problem with v4.13 ?

**Comment by nicolaskruchten** [comment]
Oh, sorry, no the problem is simply that the fix for this got bumped to 4.14 (next week) but I didn't update my comment, sorry!

**Comment by jenna-jordan** [comment]
@nicolaskruchten Did this fix get bumped again? I updated plotly and am still having this issue.

**Comment by nicolaskruchten** [comment]
I released Plotly.py 4.14 this morning and it includes this fix. Note that if you're using JupyterLab you'll need to update your extensions, and if you're using VSCode Python you'll need to wait for the vscode-jupyter extension to incorporate Plotly.js 1.58.1 in a release (which should happen next month).
