### ISSUE TITLE
graph_objs.Layout.update() method not updating annotations properly

### ISSUE THREAD

**Issue by tahouse** [plotly/plotly.py#766]
When trying to update annotations within plotly.graph_objs.Layout using the .update() method, the annotations do not appear to update properly. This may be related to issue https://github.com/plotly/plotly.js/issues/1010

To clarify, it functions correctly if the len(annotations) is the same. However, if say 1 annotation was in the original layout, but the new layout has 2 annoations, only the first is updated and the second won't appear. Perhaps an internal len(annotations) is being used and not updated?

An example is shown below (I'm using Jupyter):

```python
import plotly
import plotly.graph_objs as go
print(plotly.__version__)
plotly.offline.init_notebook_mode() # run at the start of every ipython notebook
# Create random data with numpy
import numpy as np

N = 50
random_x = np.random.randn(N)
random_y = np.random.randn(N)

# Create a trace
trace = go.Scatter(
    x = random_x,
    y = random_y,
    mode = 'markers'
)

data = [trace]

originalAnnotations=[
    go.Annotation(x=.5, y=1, xref='paper',yref='paper', text='First Annotation',showarrow=False,)
    ]
differentAnnotations=[
    go.Annotation(x=.5, y=1, xref='paper',yref='paper', text='New First Annotation',showarrow=False,),
    go.Annotation(x=.5, y=.95, xref='paper',yref='paper', text='Second Annotation',showarrow=False,)
    ]


layout=go.Layout(
    yaxis = dict(zeroline = False),
    annotations=originalAnnotations,
)
# update the layout with different annotations now.
layout.update(annotations=differentAnnotations)

# where's the second annotation?? doesn't show up in the graph
plotly.offline.iplot({"data": data,"layout": layout})

# let's try it this way
layout['annotations']=differentAnnotations
plotly.offline.iplot({"data": data,"layout": layout})

#success, but layout.update() method broken?

```

    2.0.9

![newplot-4](https://cloud.githubusercontent.com/assets/26489166/26809051/6ab25530-4a16-11e7-9fc8-0e41305c2c4d.png)

![newplot-5](https://cloud.githubusercontent.com/assets/26489166/26809053/6e1a8ada-4a16-11e7-999f-090498dda006.png)

**Comment by empet** [comment]
@tahouse  Your code is wrong, that is why the update is not performed as you want.
These two lines:
```
layout=go.Layout(
    yaxis = dict(zeroline = False),
    annotations=originalAnnotations,
)
# update the layout with different annotations now.
layout.update(annotations=differentAnnotations)
```
do the same as this simple code:

```
a=2
a=3
```


The correct way to update the annotations is to concatenate the older list of annotations with the new one:

`layout['annotations']+=differentAnnotations
`

**Comment by tahouse** [comment]
Thanks for the response, and I see your point. Of course you can simply change the dictionary value manually (i.e. not using the update method) like I did at the bottom of my post and you did your solution. However your solution is concatenates and results in three annotations -- not the two I wanted or gave the example of above. That is not an acceptable result. 

Beyond that, typing
a=2
a=3
isn't wrong in any way. You're redefining a variable, which is essential in any programming language.

Looking back at the title of the issue, "graph_objs.Layout.update() method not updating annotations properly" you gave the same workaround I used in my example code -- by not using the update method. The update method should update all of the layout parameters and it currently doesn't.

From the help(graph_objs.Layout) result:

 |  update(self, dict1=None, **dict2)
 |      Update current dict with dict1 and then dict2.
 |      
 |      This recursively updates the structure of the original dictionary-like
 |      object with the new entries in the second and third objects. This
 |      allows users to update with large, nested structures.
 |      
 |      Note, because the dict2 packs up all the keyword arguments, you can
 |      specify the changes as a list of keyword agruments.
 |      
 |      Examples:
 |      # update with dict
 |      obj = Layout(title='my title', xaxis=XAxis(range=[0,1], domain=[0,1]))
 |      update_dict = dict(title='new title', xaxis=dict(domain=[0,.8]))
 |      obj.update(update_dict)
 |      obj
 |      {'title': 'new title', 'xaxis': {'range': [0,1], 'domain': [0,.8]}}
 |      
 |      # update with list of keyword arguments
 |      obj = Layout(title='my title', xaxis=XAxis(range=[0,1], domain=[0,1]))
 |      obj.update(title='new title', xaxis=dict(domain=[0,.8]))
 |      obj
 |      {'title': 'new title', 'xaxis': {'range': [0,1], 'domain': [0,.8]}}
 |      
 |      This 'fully' supports duck-typing in that the call signature is
 |      identical, however this differs slightly from the normal update
 |      method provided by Python's dictionaries.

Otherwise the documentation needs to specify what can and can't be updated without the update method.

**Comment by empet** [comment]
@tahouse Excuse me, in the process of copying from my notebook and pasting here I've lost the line
`layout['annotations']=[]`
before:
`layout['annotations']+=differentAnnotations`

This is  just  a solution on how to perform the updating from one annotation to two annotations.
The method `Layout.update()`  seems  not working  in this case.
If you don't define layout as an instance of the class Layout,
but just as a  dict:

```
layout=dict(annotations=[dict(x=.5, y=1, xref='paper',yref='paper', 
                                                 text='FirstAnnotation',showarrow=False)])
```
then the usual update of this dict works well:

```
layout.update(annotations=[dict(x=.5, y=1, xref='paper',yref='paper', 
                                                     text='New First Annotation',showarrow=False),
                                              dict(x=.5, y=.95, xref='paper',yref='paper', 
                                                     text='Second Annotation',showarrow=False)])
```

**Comment by tahouse** [comment]
Thanks for the reply @empet . I like your solution as it allows for an update method as one would expect. I'll apply this in my own code.

I'm keeping the issue open as you've confirmed that Layout.update() seems to not be working as expected. It's only a minor annoyance that can be worked around as you've shown. Nonetheless, it should probably get fixed at some point if users are going to be encouraged to use Plotly's subclassed dictionaries. 

Thanks again!

**Comment by RafalSkolasinski** [comment]
I just noticed also a weird behaviour with ``update`` and ``annotations``.
More specifically when updating the ``layout`` without ``annotations`` it does not add it.
This simple code illustrates what I mean:
```python
>>> import plotly.graph_objs as go
>>> layout=go.Layout(title="First Plot", xaxis={'title':'x1'}, yaxis={'title':'x2'})
>>> layout.update(dict(annotations=[go.layout.Annotation(text="Highest Point", x=3, y=6)]))
>>> layout
Layout({
    'title': 'First Plot', 'xaxis': {'title': 'x1'}, 'yaxis': {'title': 'x2'}
})
```

It seems to be inconsistent with [tutorial](https://plot.ly/python/user-guide/).

**Comment by nicpayne713** [comment]
Hello, I'm on plotly 3.7.1 and ran into this very issue so I believe the update method is still broken, at least in the case of subplots.
If I call

fig = tools.make_subplots(rows=n_rows,cols=n_cols, subplot_titles=[titles])

Then the annotations are restricted to the length of the list of subplot_titles and if I call update on the annotations then it only updates as many elements in my new annotations as were originally added to the figure.

**Comment by AnitsaYovanovska** [comment]
Hi all, I was searching a lot for solution for my issue and seems I have problem mentioned in this issue. I am using plotly 4.6.0 and seems updating annotations still does not work. I am trying to plot heatmap with annotations
![image](https://user-images.githubusercontent.com/49293868/100607350-20083e00-330b-11eb-8a57-bf1523ed109d.png)
 but can not update annotations. 
![image](https://user-images.githubusercontent.com/49293868/100607446-3f06d000-330b-11eb-9c5b-d43e8d1fcb87.png)
