### ISSUE TITLE
Data API seems to not be working with strings

### ISSUE THREAD

**Issue by charleyferrari** [plotly/plotly.py#774]
I'm having issues getting `py.grid_ops.upload` to work with strings, it seems to only work with numbers.

This works for me:

```
grid = Grid([
        Column([1,2,3], 'one'),
        Column([4,5,6], 'two'),
        Column([7,8,9], 'three')
    ])

url = py.grid_ops.upload(grid, filename='test-201706140822', world_readable=False, auto_open=True)

## Run the above first, then run this

py.grid_ops.append_rows([[1,2,3]], grid = grid)

```

But when I try the exact same thing with Strings, it doesn't work for me:

```
grid = Grid([
        Column(['a','b','c'], 'one'),
        Column(['d','e','f'], 'two'),
        Column(['one', 'two', 'three'], 'three')
    ])

url = py.grid_ops.upload(grid, filename='test-201706140820', world_readable=False, auto_open=True)

## Run the above first, then run this

py.grid_ops.append_rows([['g','h','four']], grid = grid)

```

I'm using python 3.5.2 and plotly 2.0.10

**Comment by cldougl** [comment]
@charleyferrari could you check if this is a plotly.py issue or if it's and issue w/ the v2 api?

**Comment by charleyferrari** [comment]
@cldougl will do!

**Comment by charleyferrari** [comment]
@cldougl I'm still getting an error after updating via pip, should I try to build it from a pull request?

**Comment by chriddyp** [comment]
> could you check if this is a plotly.py issue or if it's and issue w/ the v2 api?

@charleyferrari - to clarify here, could you try to replicate using `requests` and constructing HTTP API requests yourself using the Plotly V2 API (https://api.plot.ly/v2).

I'd like to know if this is an issue with `plotly.py`'s implementation of this API or if it's an issue with the API itself. If it's the latter, then we should fix it at the source.

Just creating a simple, reproducable example with `requests` would be really helpful here.

**Comment by charleyferrari** [comment]
Aha, thanks. 

Just reran and I'm getting a 500 error code:

First I ran this:
```
import json
import requests
from requests.auth import HTTPBasicAuth
 
auth = HTTPBasicAuth('charleyferrari', 'wBXFyN83x1Zoi623RDlT')
headers = {'Plotly-Client-Platform': 'python'}


payload = dict(
    data = dict(
        cols = {
            'first column': dict(
                data = ['a', 'b', 'c'], order = 0
            ),
            'second column': dict(
                data = ['e', 'f', 'g'], order = 1
            )
        }
    )
)

r = requests.post('https://api.plot.ly/v2/grids', auth=auth, headers=headers, json=payload)
 
print(json.loads(r.text))
```
Got this: 

{'file': {'parent_id': -1, 'views': 0, 'parented': True, 'references': [], 'referencers': [], 'subfolder_count': None, 'share_key': 'GKASoAUI2SpH3KoyfUhm5f', 'fid': 'charleyferrari:2161', 'deleted': False, 'title': '', 'share_key_enabled': False, 'date_modified': '2017-07-07T19:03:52.206Z', 'world_readable': False, 'preview': {'second column': ['e', 'f', 'g'], 'first column': ['a', 'b', 'c']}, 'cols': [{'name': 'first column', 'uid': '406123'}, {'name': 'second column', 'uid': '6c392b'}], 'refresh_interval': None, 'api_urls': {'grids': 'https://api.plot.ly/v2/grids/charleyferrari:2161', 'files': 'https://api.plot.ly/v2/files/charleyferrari:2161', 'parent': 'https://api.plot.ly/v2/folders/home?user=charleyferrari'}, 'parent': -1, 'owner': 'charleyferrari', 'filename': 'Grid 2161', 'creation_time': '2017-07-07T19:03:52.182278Z', 'web_url': 'https://plot.ly/~charleyferrari/2161/', 'metadata': {}, 'collaborators': {'count': 0, 'results': []}, 'img_url': '', 'image_urls': {}, 'stars': {'count': 0, 'results': []}, 'filetype': 'grid', 'comments': {'count': 0, 'results': []}, 'embed_url': 'https://plot.ly/~charleyferrari/2161.embed'}}

Then ran this:

```
rows = {"rows": [['a', 'b'], ['c', 'd'], ['e', 'f']]}
 
r = requests.post('https://api.plot.ly/v2/grids/charleyferrari:2161/row', auth=auth, headers=headers, json=rows)
 
print(r.status_code)
```
and got server code 500

**Comment by Kully** [comment]
@charleyferrari 
^ I just ran the code above and didn't get an error: the graph was successfully created.

I think we can close the original issue as it is working.

**Comment by charleyferrari** [comment]
@Kully @cldougl I'm still getting the 500 error when running this on my end, but I also just realized I should have opened this up on streambed rather than plotly.py. So, I'll reopen the issue there.
